import type { Metadata } from "next";
import { Source_Sans_3, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const fontSans = Source_Sans_3({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased`}
      >
        <header className="border-b border-gray-200">
          <div className="container mx-auto py-4">
            <h1 className="text-2xl font-bold">My App</h1>
            <nav>
              <Link href="/" className="mr-4">
                Home
              </Link>
              <Link href="/about" className="mr-4">
                About
              </Link>
              <a href="/about/team" className="mr-4">
                Team
              </a>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
